### PR TITLE
Enable all tests for svn 1.10

### PR DESCRIPTION
**Pull request by dpmatthews**

### CODE REVIEW

**Comment by dpmatthews** [comment]
The test failures are caused by a bug in Subversion: https://mail-archives.apache.org/mod_mbox/subversion-users/202101.mbox/%3CCWLP265MB20020002023DA2E042EDFE6AB3A30%40CWLP265MB2002.GBRP265.PROD.OUTLOOK.COM%3E

**Comment by dpmatthews** [comment]
The svn bug is apparently fixed in 1.10.7:
https://svn.apache.org/repos/asf/subversion/tags/1.10.7/CHANGES

**Comment by dpmatthews** [comment]
All tests pass locally with svn 1.10.7.
Note: Ubuntu 20.04 tests now fail because it is using a Subversion 1.13.0 which is still affected by the bug.

**Review by wxtim — APPROVED** [review]
Makes sense. I can't test this on work or private PC without fiddling with installed SVN.

**Pull request merged**
