### PR TITLE
doc: use bootstrap 3

### PR DESCRIPTION
**Pull request by matthewrmshin**
FCM docs upgraded to use Bootstrap 3.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
@benfitzpatrick @kaday please review.

**Comment by benfitzpatrick** [comment]
I get a couple of errors in the web console for e.g. doc/installation/index.html:
```
Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3 bootstrap.min.js:6:215

The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. 1-2.html

downloadable font: download failed
```

**Comment by matthewrmshin** [comment]
Branch re-based. Update doc's copyright missed by #217. Updated jQuery version to 1.12.

**Comment by benfitzpatrick** [comment]
Glyphs display as numbered icons for file URIs (https://github.com/eclipsesource/jsonforms/issues/93). Looks like a Firefox+Bootstrap issue. We don't expect many people to ever read the documentation from a local copy - can we live with it?

**Comment by matthewrmshin** [comment]
I am happy to live with it.

**Comment by benfitzpatrick** [comment]
Looks fine to me.

**Comment by kaday** [comment]
@matthewrmshin have you missed changing some of the `well-small` to `well-sm` deliberately?

**Comment by kaday** [comment]
Should the copyright for Twitter now be 2016 like the Met Office one?

**Comment by matthewrmshin** [comment]
> Should the copyright for Twitter now be 2016 like the Met Office one?

No, because that was software released in 2015. It should left as-is.

**Comment by matthewrmshin** [comment]
> have you missed changing some of the `well-small` to `well-sm` deliberately?

Well... This small oversight has now been fixed.

**Comment by kaday** [comment]
Thanks Matt, I agree the small oversight has been fixed. Epic joke!
All looks good to me.

**Pull request merged**
