### PR TITLE
t: fix errors in VM

### PR DESCRIPTION
**Pull request by matthewrmshin**
Fix test failures in Ubuntu VM.

@dpmatthews Please test and review.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
(Branch rebased.)

Also sort display in `fcm branch-info`. 00 test should now be stable.

**Comment by matthewrmshin** [comment]
Branch re-based.

**Comment by dpmatthews** [comment]
The tests now pass on the Ubuntu 1404 & 1504 VMs.
@benfitzpatrick - could you review please.

**Comment by matthewrmshin** [comment]
`./t/fcm-switch/00-simple.t` test 2 appears to still fail randomly with:

```diff
--- /tmp/tmp.??????/00-simple-trunk.sorted.out	2015-10-19 21:14:14.404077657 +0000
+++ -	2015-10-19 21:14:14.406562358 +0000
@@ -1,8 +1,8 @@
 switch: status of "/tmp/tmp.eMl8a06ekj/wc":
 ?       unversioned_file
 switch: continue?
-Enter "y" or "n" (or just press <return> for "n"): D    added_directory
-D    added_file
+Enter "y" or "n" (or just press <return> for "n"): D    added_file
+D    added_directory
 D    module/tree_conflict_file
 U    lib/python/info/__init__.py
 U    lib/python/info/poems.py
```

**Comment by dpmatthews** [comment]
`./t/fcm-switch/01-subtree.t` test 2 also appears to still fail randomly with a similar error.

**Comment by matthewrmshin** [comment]
The randomly failing problem is due to instability in Subversion output.

**Comment by matthewrmshin** [comment]
Tests should now be stable.

**Comment by benfitzpatrick** [comment]
Looks fine and test battery passes (here)!

**Pull request merged**
